---
- name: Audit | Execute Bootloader chapter controls
  ansible.builtin.include_tasks: bootloader.yml
  tags: [cis, audit, astra, bootloader, chapter_bootloader]

- name: Audit | Execute Process Hardening chapter controls
  ansible.builtin.include_tasks: process_hardening.yml
  tags: [cis, audit, astra, process_hardening, chapter_process_hardening]

- name: Audit | Execute Time Sync chapter controls
  ansible.builtin.include_tasks: timesync.yml
  tags: [cis, audit, astra, timesync, chapter_timesync]

- name: Audit | Execute Banners chapter controls
  ansible.builtin.include_tasks: banners.yml
  tags: [cis, audit, astra, banners, chapter_banners]

- name: Audit | Execute Network Kernel Modules chapter controls
  ansible.builtin.include_tasks: network_kernel_modules.yml
  tags: [cis, audit, astra, network_kernel_modules, chapter_network_kernel_modules]

- name: Audit | Execute Logging chapter controls
  ansible.builtin.include_tasks: logging.yml
  tags: [cis, audit, astra, logging, chapter_logging]

- name: Audit | Execute Services chapter controls
  ansible.builtin.include_tasks: services.yml
  tags: [cis, audit, astra, services, chapter_services]

- name: Audit | Execute Filesystem chapter controls
  ansible.builtin.include_tasks: filesystem.yml
  tags: [cis, audit, astra, filesystem, chapter_filesystem]

- name: Audit | Execute SUDO chapter controls
  ansible.builtin.include_tasks: sudo.yml
  tags: [cis, audit, astra, sudo, chapter_sudo]

- name: Audit | Execute PAM chapter controls
  ansible.builtin.include_tasks: pam.yml
  tags: [cis, audit, astra, pam, chapter_pam]

- name: Audit | Execute Cron&At chapter controls
  ansible.builtin.include_tasks: cron_at.yml
  tags: [cis, audit, astra, cron_at, chapter_cron_at]

- name: Audit | Execute SSHD chapter controls
  ansible.builtin.include_tasks: sshd.yml
  tags: [cis, audit, astra, sshd, chapter_sshd]

- name: Audit | Execute Local Users and Groups chapter controls
  ansible.builtin.include_tasks: local_users_groups.yml
  tags: [cis, audit, astra, local_users_groups, chapter_local_users_groups]

- name: Audit | Execute FilePermission chapter controls
  ansible.builtin.include_tasks: file_permission.yml
  tags: [cis, audit, astra, file_permission, chapter_file_permission]

- name: Audit | Execute Passwords chapter controls
  ansible.builtin.include_tasks: passwords.yml
  tags: [cis, audit, astra, passwords, chapter_passwords]

- name: Audit | Execute Root&System Accounts chapter controls
  ansible.builtin.include_tasks: root_system_accounts.yml
  tags: [cis, audit, astra, root_system_accounts, chapter_root_system_accounts]
